### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by shantanuo** [mkonicek/nlp#1]
I am using fasttext pre-trained model based on english wikipedia. It works as expected...

https://github.com/shantanuo/pandas_examples/blob/master/nlp/fasttext_english.ipynb

But when I try the same code with some other language, I get an error as shown on this page...

https://github.com/shantanuo/pandas_examples/blob/master/nlp/fasttext_marathi.ipynb

The error is related to unicode:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 15: invalid start byte

I tried to open the file using Raw Binary option. I changed the function load_words_raw in load.py file:

    with open(file_path, 'rb') as f:

And now I get a different error:

ValueError: could not convert string to float: b'\x00l\x02'

I have no idea how to handle this.

**Comment by mkonicek** [comment]
Heya, I haven't seen this error but Googled "can't decode byte 0x80" and found this:
- https://stackoverflow.com/questions/38518023/unicodedecodeerror-utf8-codec-cant-decode-byte-0x80-in-position-3131-invali
- https://github.com/Currie32/Spell-Checker/issues/14

Based on the number of Google results this looks like a relatively common Python error. Do any of those links help?

**Comment by shantanuo** [comment]
Yes. That helped. Thanks and closing.
